spring:
  application:
    name: bankwise

  port: 9090

  mongodb:
    uri: ${MONGODB_URI}
    database: bankwise-db
    representation:
      uuid: STANDARD

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai/v1
      chat:
        options:
          model: llama-3.3-70b-versatile

bankwise:
  storage:
    document-path: ${DOCUMENT_STORAGE_PATH:./storage/documents}
  document:
    max-file-size: 10485760
    chunking:
      chunk-size: 1000
      overlap: 200

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:NGE1ZThjMWY5ZDNiMmE0ZTZmOGMwYjJkNGU2ZjhhMGIxYzNkNWU3ZjlhMmI0YzZkOGUwZjFhM2I1YzdkOWUxZg==}
      expiration: 900000


